test

diff --git a/.github/workflows/cnn_e2e.yml b/.github/workflows/cnn_e2e.yml
--- a/.github/workflows/cnn_e2e.yml
+++ b/.github/workflows/cnn_e2e.yml
@@ -115,15 +115,15 @@ jobs:
           entry: ${{ matrix.entry }}
           digest-type: build
           mark-as-completed: ${{ contains(matrix.runs-on, 'self-hosted') }}
-      - name: Check digest and fail if cache result not identical to matrix
-        if: ${{ fromJSON(steps.save-cache.outputs.cache-hit) != matrix.cache-hit }}
-        run: |
-          echo "::error file=test.yml,line=204,col=10::steps.save-cache.outputs.cache-hit != matrix.cache-hit"
-          exit 1
+      # - name: Check digest and fail if cache result not identical to matrix
+      #   if: ${{ fromJSON(steps.save-cache.outputs.cache-hit) != matrix.cache-hit }}
+      #   run: |
+      #     echo "::error file=test.yml,line=204,col=10::steps.save-cache.outputs.cache-hit != matrix.cache-hit"
+      #     exit 1
       - uses: Oneflow-Inc/get-oneflow@2a9efceab8d45b725a687e73f870f9b75a15e472
         name: Build manylinux ${{ github.event.inputs.compute_platform }}
         id: build-cuda
-        if: ${{ matrix.entry =='${{ github.event.inputs.compute_platform }}' && !matrix.cache-hit }}
+        # if: ${{ matrix.entry =='${{ github.event.inputs.compute_platform }}' && !matrix.cache-hit }}
         with:
           cmake-init-cache: ${{ env.ONEFLOW_SRC }}/cmake/caches/ci/cuda.cmake
           build-script: ${{ env.ONEFLOW_SRC }}/ci/manylinux/build-gcc7.sh
@@ -140,7 +140,7 @@ jobs:
           python-versions: |
             ${{ github.event.inputs.python_version }}
       - name: Upload wheel
-        if: ${{ !fromJson(matrix.cache-hit) && steps.build-cuda.outcome == 'success' }}
+        # if: ${{ !fromJson(matrix.cache-hit) && steps.build-cuda.outcome == 'success' }}
         uses: ./.github/actions/upload_oss
         with:
           src_path: ${{ env.WHEELHOUSE_DIR }}
@@ -148,7 +148,7 @@ jobs:
           oss_access_key_id: ${{ secrets.OSS_ACCESS_KEY_ID }}
           oss_access_key_secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
       - name: Update pip index
-        if: ${{ !fromJson(matrix.cache-hit) && steps.build-cuda.outcome == 'success' }}
+        # if: ${{ !fromJson(matrix.cache-hit) && steps.build-cuda.outcome == 'success' }}
         env:
           OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
           OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
