test

diff --git a/.github/workflows/cnn_e2e.yml b/.github/workflows/cnn_e2e.yml
--- a/.github/workflows/cnn_e2e.yml
+++ b/.github/workflows/cnn_e2e.yml
@@ -106,56 +106,56 @@ jobs:
           echo "oss_dir=${oss_dir}" >> $GITHUB_ENV
           cd $current_dir
           set +x
-      # - uses: Oneflow-Inc/get-oneflow/cache-complete@2a9efceab8d45b725a687e73f870f9b75a15e472
-      #   name: Save cache if successful
-      #   id: save-cache
-      #   timeout-minutes: 5
-      #   with:
-      #     oneflow-src: ${{ env.ONEFLOW_SRC }}
-      #     entry: ${{ matrix.entry }}
-      #     digest-type: build
-      #     mark-as-completed: ${{ contains(matrix.runs-on, 'self-hosted') }}
-      # - name: Check digest and fail if cache result not identical to matrix
-      #   if: ${{ fromJSON(steps.save-cache.outputs.cache-hit) != matrix.cache-hit }}
-      #   run: |
-      #     echo "::error file=test.yml,line=204,col=10::steps.save-cache.outputs.cache-hit != matrix.cache-hit"
-      #     exit 1
-      # - uses: Oneflow-Inc/get-oneflow@2a9efceab8d45b725a687e73f870f9b75a15e472
-      #   name: Build manylinux ${{ github.event.inputs.compute_platform }}
-      #   id: build-cuda
-      #   if: ${{ matrix.entry =='${{ github.event.inputs.compute_platform }}' && !matrix.cache-hit }}
-      #   with:
-      #     cmake-init-cache: ${{ env.ONEFLOW_SRC }}/cmake/caches/ci/cuda.cmake
-      #     build-script: ${{ env.ONEFLOW_SRC }}/ci/manylinux/build-gcc7.sh
-      #     oneflow-src: ${{ env.ONEFLOW_SRC }}
-      #     oneflow-build-env: manylinux
-      #     wheelhouse-dir: ${{ env.WHEELHOUSE_DIR }}
-      #     clear-wheelhouse-dir: true
-      #     self-hosted: true
-      #     cuda-version: "11.2"
-      #     manylinux-cache-dir: ${{ env.MANYLINUX_CACHE_DIR }}
-      #     docker-run-use-system-http-proxy: false
-      #     docker-run-use-lld: false
-      #     retry-failed-build: true
-      #     python-versions: |
-      #       ${{ github.event.inputs.python_version }}
-      # - name: Upload wheel
-      #   if: ${{ !fromJson(matrix.cache-hit) && steps.build-cuda.outcome == 'success' }}
-      #   uses: ./.github/actions/upload_oss
-      #   with:
-      #     src_path: ${{ env.WHEELHOUSE_DIR }}
-      #     oss_dst_path: oss://oneflow-staging/${{ env.oss_dir }}
-      #     oss_access_key_id: ${{ secrets.OSS_ACCESS_KEY_ID }}
-      #     oss_access_key_secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
-      # - name: Update pip index
-      #   if: ${{ !fromJson(matrix.cache-hit) && steps.build-cuda.outcome == 'success' }}
-      #   env:
-      #     OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
-      #     OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
-      #   run: |
-      #     python3 -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
-      #     python3 -m pip install oss2 beautifulsoup4 --user
-      #     python3 tools/create_pip_index.py --dir_key ${oss_dir} -b oneflow-staging --index_key=${oss_branch_dir}/index.html --index_key=${oss_dir}/index.html
+      - uses: Oneflow-Inc/get-oneflow/cache-complete@2a9efceab8d45b725a687e73f870f9b75a15e472
+        name: Save cache if successful
+        id: save-cache
+        timeout-minutes: 5
+        with:
+          oneflow-src: ${{ env.ONEFLOW_SRC }}
+          entry: ${{ matrix.entry }}
+          digest-type: build
+          mark-as-completed: ${{ contains(matrix.runs-on, 'self-hosted') }}
+      - name: Check digest and fail if cache result not identical to matrix
+        if: ${{ fromJSON(steps.save-cache.outputs.cache-hit) != matrix.cache-hit }}
+        run: |
+          echo "::error file=test.yml,line=204,col=10::steps.save-cache.outputs.cache-hit != matrix.cache-hit"
+          exit 1
+      - uses: Oneflow-Inc/get-oneflow@2a9efceab8d45b725a687e73f870f9b75a15e472
+        name: Build manylinux ${{ github.event.inputs.compute_platform }}
+        id: build-cuda
+        if: ${{ matrix.entry =='${{ github.event.inputs.compute_platform }}' && !matrix.cache-hit }}
+        with:
+          cmake-init-cache: ${{ env.ONEFLOW_SRC }}/cmake/caches/ci/cuda.cmake
+          build-script: ${{ env.ONEFLOW_SRC }}/ci/manylinux/build-gcc7.sh
+          oneflow-src: ${{ env.ONEFLOW_SRC }}
+          oneflow-build-env: manylinux
+          wheelhouse-dir: ${{ env.WHEELHOUSE_DIR }}
+          clear-wheelhouse-dir: true
+          self-hosted: true
+          cuda-version: "11.2"
+          manylinux-cache-dir: ${{ env.MANYLINUX_CACHE_DIR }}
+          docker-run-use-system-http-proxy: false
+          docker-run-use-lld: false
+          retry-failed-build: true
+          python-versions: |
+            ${{ github.event.inputs.python_version }}
+      - name: Upload wheel
+        if: ${{ !fromJson(matrix.cache-hit) && steps.build-cuda.outcome == 'success' }}
+        uses: ./.github/actions/upload_oss
+        with:
+          src_path: ${{ env.WHEELHOUSE_DIR }}
+          oss_dst_path: oss://oneflow-staging/${{ env.oss_dir }}
+          oss_access_key_id: ${{ secrets.OSS_ACCESS_KEY_ID }}
+          oss_access_key_secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
+      - name: Update pip index
+        if: ${{ !fromJson(matrix.cache-hit) && steps.build-cuda.outcome == 'success' }}
+        env:
+          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
+          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
+        run: |
+          python3 -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
+          python3 -m pip install oss2 beautifulsoup4 --user
+          python3 tools/create_pip_index.py --dir_key ${oss_dir} -b oneflow-staging --index_key=${oss_branch_dir}/index.html --index_key=${oss_dir}/index.html
 
   # test:
   #   name: Test suite
