test

diff --git a/.github/workflows/cnn_e2e.yml b/.github/workflows/cnn_e2e.yml
--- a/.github/workflows/cnn_e2e.yml
+++ b/.github/workflows/cnn_e2e.yml
@@ -60,8 +60,8 @@ jobs:
       ONEFLOW_SRC: oneflow-src
       MANYLINUX_CACHE_DIR: ~/manylinux-cache-dir/${{ matrix.entry }}
       WHEELHOUSE_DIR: manylinux-wheelhouse
-      SSH_TANK_HOST: 192.168.1.22
-      SSH_TANK_PATH: /tmp
+      SSH_TANK_HOST: 192.168.1.23
+      SSH_TANK_PATH: /home/ci-user/tank
       OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
       OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
     steps:
@@ -78,6 +78,20 @@ jobs:
           repository: Oneflow-Inc/oneflow
           ref: ${{ github.event.inputs.of_branch_or_commit }}
           path: ${{ env.ONEFLOW_SRC }}
+      - uses: Oneflow-Inc/get-oneflow/cache-complete@2a9efceab8d45b725a687e73f870f9b75a15e472
+        name: Save cache if successful
+        id: save-cache
+        timeout-minutes: 5
+        with:
+          oneflow-src: ${{ env.ONEFLOW_SRC }}
+          entry: ${{ matrix.entry }}
+          digest-type: build
+          mark-as-completed: ${{ contains(matrix.runs-on, 'self-hosted') }}
+      - name: Check digest and fail if cache result not identical to matrix
+        if: ${{ fromJSON(steps.save-cache.outputs.cache-hit) != matrix.cache-hit }}
+        run: |
+          echo "::error file=test.yml,line=204,col=10::steps.save-cache.outputs.cache-hit != matrix.cache-hit"
+          exit 1
       - uses: Oneflow-Inc/get-oneflow@2a9efceab8d45b725a687e73f870f9b75a15e472
         name: Build manylinux cu102
         id: build-cuda
