test

diff --git a/.github/workflows/cnn_e2e.yml b/.github/workflows/cnn_e2e.yml
--- a/.github/workflows/cnn_e2e.yml
+++ b/.github/workflows/cnn_e2e.yml
@@ -12,6 +12,8 @@ on:
         default: 'master'
 env:
   ONEFLOW_SRC: oneflow-src
+  SSH_TANK_HOST: 192.168.1.23
+  SSH_TANK_PATH: /home/ci-user/tank
 jobs:
   cancel_previous:
     name: Cancel previous runs
@@ -26,7 +28,6 @@ jobs:
     name: "Find build cache"
     runs-on: ubuntu-latest
     env:
-      # ONEFLOW_SRC: oneflow-src
       OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
       OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
     outputs:
@@ -59,11 +60,8 @@ jobs:
       max-parallel: 5
       matrix: ${{ fromJson(needs.find-build-cache.outputs.matrix) }}
     env:
-      # ONEFLOW_SRC: oneflow-src
       MANYLINUX_CACHE_DIR: ~/manylinux-cache-dir/${{ matrix.entry }}
       WHEELHOUSE_DIR: manylinux-wheelhouse
-      SSH_TANK_HOST: 192.168.1.23
-      SSH_TANK_PATH: /home/ci-user/tank
       OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
       OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
     steps:
@@ -136,8 +134,6 @@ jobs:
     name: "Find test cache"
     runs-on: ubuntu-latest
     needs: [build-manylinux]
-    # env:
-    #   ONEFLOW_SRC: oneflow-src
     outputs:
       matrix: ${{ steps.find-cache.outputs.matrix }}
     steps:
@@ -156,6 +152,53 @@ jobs:
             self-hosted
             linux
           oneflow-src: ${{ env.ONEFLOW_SRC }}
+  test:
+    name: Test suite
+    needs: [wait_for_gpu_slot, find-test-cache]
+    runs-on: ${{ matrix.runs-on }}
+    strategy:
+      fail-fast: true
+      max-parallel: 5
+      matrix: ${{ fromJson(needs.find-test-cache.outputs.matrix) }}
+    env:
+      TEST_CONTAINER_NAME: "oneflow_benchmark-run-id-${{ github.run_id }}-${{ matrix.entry }}-test"
+    steps:
+      - name: Fix permissions
+        if: ${{ contains(matrix.runs-on, 'self-hosted') }}
+        run: |
+          set -x
+          docker run --rm -v $PWD:/p -w /p busybox chown -R $(id -u):$(id -g) .
+      - name: Checkout Oneflow-Inc/OneFlow-Benchmark
+        uses: actions/checkout@v2
+      - name: Remove container
+        timeout-minutes: 45
+        if: ${{ contains(matrix.runs-on, 'self-hosted') }}
+        run: |
+          docker rm -f ${{ env.TEST_CONTAINER_NAME }} || true
+      - uses: Oneflow-Inc/get-oneflow/cache-complete@2a9efceab8d45b725a687e73f870f9b75a15e472
+        name: Save cache if successful
+        id: save-cache
+        timeout-minutes: 5
+        with:
+          oneflow-src: ${{ env.ONEFLOW_SRC }}
+          entry: ${{ matrix.entry }}
+          digest-type: ${{ matrix.digest-type }}
+          mark-as-completed: ${{ contains(matrix.runs-on, 'self-hosted') }}
+      - name: Check digest and fail if cache result not identical to matrix
+        if: ${{ fromJSON(steps.save-cache.outputs.cache-hit) != matrix.cache-hit }}
+        run: |
+          echo "::error file=test.yml,line=204,col=10::steps.save-cache.outputs.cache-hit != matrix.cache-hit"
+          exit 1
+      - name: Download wheel and binary
+        if: ${{ !fromJson(matrix.cache-hit) && contains(matrix.runs-on, 'self-hosted') && (!fromJson(matrix.is-xla) || (fromJson(matrix.is-xla) && needs.changed_files.outputs.should_run_single_client_tests == '1')) }}
+        uses: Oneflow-Inc/get-oneflow/degist/download@2a9efceab8d45b725a687e73f870f9b75a15e472
+        id: download-digest
+        timeout-minutes: 10
+        with:
+          digest: ${{ steps.save-cache.outputs.build-digest }}
+          entry: ${{ matrix.compute-platform }}
+          ssh-tank-host: ${{ env.SSH_TANK_HOST }}
+          ssh-tank-path: ${{ env.SSH_TANK_PATH }}
   # build: 
   #   name: 'Build and test this repo'
   #   runs-on: ['self-hosted', 'linux', 'provision']
